configuration/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.donnees_machines, name='donnees_machines'),
    path("add_machine", views.add_machine, name="add_machine"),
    path("add_user", views.add_user, name="add_user"),
    path("add_oid", views.add_oid, name="add_oid"),
    path("add_machine_has_OID/<str:key>/", views.add_machine_has_OID, name="add_machine_has_OID"),
    path("add_graphique_has_machine/<int:key>/", views.add_graphique_has_machine, name="add_graphique_has_machine"),
    path("add_graphique", views.add_graphique, name="add_graphique"),
    path('machines', views.liste_machines, name='liste_machines'),
    path('oids', views.liste_oids, name='liste_oids'),
    path('graphiques', views.liste_graphiques, name='liste_graphiques'),
    path('users', views.liste_users, name='liste_users'),
    path('logs', views.logs, name='logs'),
    path('edit_machine/<int:machine_id>/', views.edit_machine, name='edit_machine'),
    path('edit_graphique_machine/<int:graphique_machine_id>/', views.edit_graphique_machine, name='edit_graphique_machine'),
    path('delete_machine/<int:machine_id>/', views.delete_machine, name='delete_machine'),
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('edit_oid/<int:oid_id>/', views.edit_oid, name='edit_oid'),
    path('edit_graphique/<int:graphique_id>/', views.edit_graphique, name='edit_graphique'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('delete_oid/<int:oid_id>/', views.delete_oid, name='delete_oid'),
    path('delete_machine_has_OID/<int:machine_oid_id>/', views.delete_machine_has_OID, name='delete_machine_has_OID'),
    path('delete_graphique_has_machine/<int:graphique_machine_id>/', views.delete_graphique_has_machine, name='delete_graphique_has_machine'),
    path('delete_graphique/<int:graphique_id>/', views.delete_graphique, name='delete_graphique'),
    path('donnees_machines', views.donnees_machines, name='donnees_machines'),
    path('download-log/', views.download_log, name='download_log'),
]

loginpage/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path("", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
]

supervision/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect

urlpatterns = [
    path("menu_principal/", include("configuration.urls")),
    path("loginpage/", include("django.contrib.auth.urls")),
    path("loginpage/", include("loginpage.urls")),
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('menu_principal/', permanent=True)),
]

configuration/models.py
from django.db import models
from django.utils import timezone

class Machine(models.Model):
    name = models.CharField(max_length=255)
    IPAdresse = models.GenericIPAddressField()
    port = models.IntegerField(default=161)
    SNMP_CHOICES = [
        ('1', 'Version 1'),
        ('2c', 'Version 2c'),
        ('3', 'Version 3')
    ]
    SNMPType = models.CharField(max_length=3, choices=SNMP_CHOICES, default='1')
    Community = models.CharField(max_length=255, default=None)
    
    def __str__(self):
        return self.name
    
class OID(models.Model):
    name = models.CharField(max_length=255)
    oid = models.CharField(max_length=255)
    Donnee_fixe = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name
    
class SurveillanceManager(models.Model):
    idMachine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    information_type = models.CharField(max_length=255)
    date = models.DateTimeField(default=timezone.now)
    data = models.CharField(max_length=255)
    
    def __str__(self):
        return self.idMachine.name + " " +self.information_type + " " + str(self.date)

class Logs(models.Model):
    date = models.DateTimeField(default=timezone.now)
    idMachine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    type_log = models.CharField(max_length=255)
    informations = models.CharField(max_length=255)
    is_error = models.BooleanField(default=False)
    
    def __str__(self):
        return self.idMachine.name + " " +self.type_log + " " + str(self.date)
    
class Graphique(models.Model):
    name = models.CharField(max_length=255)
    Graphique_Types = [
        ('Fleche', 'Fleche'),
        ('Curseur', 'Curseur'),
        ('Texte', 'Texte')
    ]
    GraphiqueType = models.CharField(max_length=255,choices=Graphique_Types, default='1')
    axex = models.CharField(max_length=255, blank=True, null=True)
    axey = models.CharField(max_length=255, blank=True, null=True)
    OID1 = models.ForeignKey(OID, on_delete=models.CASCADE, related_name='OID1')
    OID2 = models.ForeignKey(OID, on_delete=models.CASCADE, related_name='OID2', blank=True, null=True)
    valeur_max = models.IntegerField(default=0)
    Donnees_Types = [
        ('Texte', 'Texte'), 
        ('Entier', 'Entier'), 
        ('Boolean', 'Boolean'),    
        ('Heure', 'Heure'),
        ('Minute', 'Minute'),
        ('Seconde', 'Seconde'),
        ('CentSeconde', 'CentSeconde'),
        ('Ratio', 'Ratio'),
        ('Pourcentage', 'Pourcentage')
    ]
    type_de_donnees_entree = models.CharField(max_length=255,choices=Donnees_Types, default='Texte')
    type_de_donnees_sortie = models.CharField(max_length=255,choices=Donnees_Types, default='Texte')
    def __str__(self):
        return self.name

class Machine_has_OID(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    OID = models.ForeignKey(OID, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.machine.name + " " +  self.OID.name

class Graphique_has_Machine(models.Model):
    graphique = models.ForeignKey(Graphique, on_delete=models.CASCADE)
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    ordre = models.IntegerField(default=1)
    
    def __str__(self):
        return self.graphique.name + " "+ self.machine.name
    

configuration/views.py
from .models import Machine, OID, SurveillanceManager, Logs, Graphique, Machine_has_OID, Graphique_has_Machine
from .forms import MachineForm, UtilisateurForm, OIDForm, GraphiqueForm, GetMachineForm, MachinehasOIDForm, GraphiquehasMachineForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.conf import settings 
import os
from django.http import HttpResponse
import math

@login_required
def index(request):
    return render(request, 'index.html')

""" CRUD MACHINE """

@login_required
def add_machine(request):
    form = MachineForm()  # Initialiser le formulaire pour les requêtes GET

    if request.method == 'POST' and 'add_machine' in request.POST:
        form = MachineForm(request.POST)  
        if form.is_valid():
            form.save()
            return redirect("liste_machines")

    return render(request, 'add_configuration.html', {'form': form})

@login_required
def liste_machines(request):
    machines = Machine.objects.all()
    return render(request, 'liste_machines.html', {'machines': machines})

@login_required
def edit_machine(request, machine_id):
    machine = get_object_or_404(Machine, id=machine_id)
    if request.method == 'POST':
        form = MachineForm(request.POST, instance=machine)
        if form.is_valid():
            form.save()
            return redirect('liste_machines')
    else:
        form = MachineForm(instance=machine)
    return render(request, 'edit_machine.html', {'form': form})

@login_required
def delete_machine(request, machine_id):
    machine = get_object_or_404(Machine, id=machine_id)
    if request.method == 'POST':
        machine.delete()
        return redirect('liste_machines')
    return render(request, 'confirm_delete_machines.html', {'object': machine})

""" CRUD UTILISATEUR """

@login_required
def add_user(request):
    form = UtilisateurForm()

    if request.method == 'POST' and 'add_user' in request.POST:
        form = UtilisateurForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['login']
            password = form.cleaned_data['password']
            last_name = form.cleaned_data['last_name']
            first_name = form.cleaned_data['first_name']
            email = form.cleaned_data['mail']  # Note: User model utilise 'email' plutôt que 'mail'
            is_admin = form.cleaned_data['is_admin']

            # Utilisez create_user pour le hachage correct du mot de passe
            user = User.objects.create_user(username=username, password=password, email=email, 
                                            first_name=first_name, last_name=last_name)
            
            if is_admin:
                user.is_superuser = True
                user.is_staff = True
                user.save()
            else: 
                user.is_superuser = False
                user.is_staff = False
                user.save()
                

            return redirect("liste_users")
        else:
            print(form.errors)

    return render(request, 'add_utilisateur.html', {'form': form})

@login_required
def liste_users(request):
    users = User.objects.all()
    return render(request, 'liste_users.html', {'users': users})


@login_required
def delete_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        user.delete()
        return redirect('liste_users')
    return render(request, 'confirm_delete_users.html', {'object': user})


@login_required
def edit_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        form = UtilisateurForm(request.POST)
        if form.is_valid():
            user.username = form.cleaned_data['login']
            user.last_name = form.cleaned_data['last_name']
            user.first_name = form.cleaned_data['first_name']
            user.email = form.cleaned_data['mail'] 
                        
            if form.cleaned_data['password'] != ""   :
                user.set_password(form.cleaned_data['password'])
            
            is_admin = form.cleaned_data['is_admin']
            
            if is_admin:
                user.is_superuser = True
                user.is_staff = True
            else:
                user.is_superuser = False
                user.is_staff = False
            
            user.save()
        
            return redirect('liste_users')
    else:
        form = UtilisateurForm(initial={
    'login': user.username,
    'last_name': user.last_name,
    'first_name': user.first_name,
    'is_admin': user.is_superuser,
    'mail': user.email
})
    
    return render(request, 'edit_user.html', {'form': form})

""" CRUD OIDS """

@login_required
def add_oid(request):
    form = OIDForm()  # Initialiser le formulaire pour les requêtes GET

    if request.method == 'POST' and 'add_oid' in request.POST:
        form = OIDForm(request.POST)  
        if form.is_valid():
            form.save()
            return redirect("liste_oids")
        else:
            print(form.errors)

    return render(request, 'add_oid.html', {'form': form})

@login_required
def liste_oids(request):
    oids = OID.objects.all()
    machines_oids = Machine_has_OID.objects.all()
    
    dictionary = {}
    for oid in oids :
        dictionary.update({oid: list(Machine_has_OID.objects.all().filter(OID=oid))})
    
    return render(request, 'liste_oids.html', {'oids': oids, 'dictionary': dictionary, 'machines_oids':machines_oids})

@login_required
def edit_oid(request, oid_id):
    oid = get_object_or_404(OID, id=oid_id)
    if request.method == 'POST':
        form = OIDForm(request.POST , instance=oid)
        if form.is_valid():
            form.save()
            return redirect('liste_oids')
    else:
        form = OIDForm(instance=oid)
    
    return render(request, 'edit_oid.html', {'form': form})


@login_required
def delete_oid(request, oid_id):
    oid = get_object_or_404(OID, id=oid_id)
    if request.method == 'POST':
        oid.delete()
        return redirect('liste_oids')
    return render(request, 'confirm_delete_oids.html', {'object': oid})

""" ADD and DELETE Machine_has_OID"""

@login_required
def add_machine_has_OID(request, key):
    OID_machine = OID.objects.get(name=key)  

    if request.method == 'POST' and 'add_machine_oid' in request.POST:
        form = MachinehasOIDForm(request.POST)  
        if form.is_valid():
            machine_value = form.cleaned_data['machine']
            oid_value = form.cleaned_data['OID']
            if not Machine_has_OID.objects.filter(OID=oid_value, machine=machine_value).exists() :
                form.save()
            return redirect("liste_oids")
        else:
            print(form.errors)
    else: 
        form = MachinehasOIDForm(initial={'OID': OID_machine})

    return render(request, 'add_machine_oid.html', {'form': form, 'OID_machine': OID_machine})


@login_required
def delete_machine_has_OID(request, machine_oid_id):
    machine_oid = get_object_or_404(Machine_has_OID, id=machine_oid_id)
    if request.method == 'POST':
        machine_oid.delete()
        return redirect('liste_oids')
    return render(request, 'confirm_delete_machine_oid.html', {'object': machine_oid})

""" ADD, EDIT and DELETE Graphique_has_Machine"""

@login_required
def add_graphique_has_machine(request, key):
    graphique_machine = get_object_or_404(Graphique, id=key)

    if request.method == 'POST' and 'add_graphique_machine' in request.POST:
        form = GraphiquehasMachineForm(request.POST, graphique=graphique_machine)  
        if form.is_valid():
            machine_value = form.cleaned_data['machine']
            graphique_value = form.cleaned_data['graphique']
            if not Graphique_has_Machine.objects.filter(graphique=graphique_value, machine=machine_value).exists() :
                form.save()
            return redirect("liste_graphiques")
        else:
            print(form.errors)
    else: 
        form = GraphiquehasMachineForm(graphique=graphique_machine)

    return render(request, 'add_graphique_machine.html', {'form': form, 'graphique_machine': graphique_machine})


@login_required
def delete_graphique_has_machine(request, graphique_machine_id):
    graphique_machine = get_object_or_404(Graphique_has_Machine, id=graphique_machine_id)
    if request.method == 'POST':
        graphique_machine.delete()
        return redirect('liste_graphiques')
    return render(request, 'confirm_delete_graphique_machine.html', {'object': graphique_machine})


@login_required
def edit_graphique_machine(request, graphique_machine_id):
    graphique_machine = get_object_or_404(Graphique_has_Machine, id=graphique_machine_id)
    graphique_instance = graphique_machine.graphique

    if request.method == 'POST':
        form = GraphiquehasMachineForm(request.POST, instance=graphique_machine, graphique=graphique_instance)
        if form.is_valid():
            form.save()
            return redirect('liste_graphiques')
    else:
        form = GraphiquehasMachineForm(instance=graphique_machine, graphique=graphique_instance)
    
    return render(request, 'edit_graphique_machine.html', {'form': form})



""" CRUD Graphiques """

@login_required
def add_graphique(request):
    form = GraphiqueForm()  # Initialiser le formulaire pour les requêtes GET

    if request.method == 'POST' and 'add_graphique' in request.POST:
        form = GraphiqueForm(request.POST)  
        if form.is_valid():
            form.save()
            return redirect("liste_graphiques")
        else:
            print(form.errors)

    return render(request, 'add_graphique.html', {'form': form})

@login_required
def liste_graphiques(request):
    graphiques = Graphique.objects.all()
    machines = Machine.objects.all()
    
    dictionary_machines = {}
    for machine in machines :

configuration/templates/add_graphique.html
{% include 'template.html' %} 
<form class="item" method="POST">
    {% csrf_token %}
    <p><strong>Pour ajouter un graphique : </strong></p>

    <p>Nom :</p>
    {{ form.name }}

    <p>Type de graphique :</p>
    {{ form.GraphiqueType }}
    
    <div id="axes-section" style="display:none;">
    <p>Axe x :</p>
    {{ form.axex }}
    
    <p>Axe y :</p>
    {{ form.axey }}
    </div>
    
    <p>OID 1 :</p>
    {{ form.OID1 }}
    
     <div id="oid2-section" style="display:none;">
        <p>OID 2 :</p>
        {{ form.OID2 }}
     </div>
    
     <div id="valeur-max-section" style="display:none;">
        <p>Valeur max :</p>
        {{ form.valeur_max }}
     </div>
    
     <p>Valeur en entrée </p>
     {{ form.type_de_donnees_entree }}
     
      <p>Valeur en sortie</p>
      {{ form.type_de_donnees_sortie }}
    
    <script>
    function toggleFields() {
        var typeSelect = document.querySelector("[name='GraphiqueType']");
        var selectedType = typeSelect.value;

        // Masquer ou afficher les champs en fonction du type sélectionné
        var showAxes = selectedType !== "Texte" && selectedType !== "Curseur";
        var showOID2 = selectedType !== "Texte" && selectedType !== "Curseur";
        var showValeurMax = selectedType !== "Texte" && selectedType !== "Fleche";

        document.getElementById('axes-section').style.display = showAxes ? 'block' : 'none';
        document.getElementById('oid2-section').style.display = showOID2 ? 'block' : 'none';
        document.getElementById('valeur-max-section').style.display = showValeurMax ? 'block' : 'none';
    }

    document.querySelector("[name='GraphiqueType']").addEventListener('change', toggleFields);

    // Exécuter la fonction au chargement de la page
    toggleFields();
    </script>
    
    <br/><br/>
    <input class="button_cursor" type="submit" name="add_graphique" value="Ajouter un graphique" />
    <br/><br/>
    <a href="{% url 'liste_graphiques' %}">Retour à la liste des graphiques</a>
</form>

configuration/templates/add_machine_oid.html
{% include 'template.html' %} 
<form class="item" method="POST">
    {% csrf_token %}
    <p><strong>Pour ajouter une machine à un OID : </strong></p>

    <p>OID :</p>
    {{ form.OID }}
    
    <p>Machine :</p>
    {{ form.machine }}

    <br/><br/>
    <input class="button_cursor" type="submit" name="add_machine_oid" value="Ajouter une machine à un oid" />
    <br/><br/>
    <a href="{% url 'liste_oids' %}">Retour à la liste des OIDs</a>
</form>

configuration/templates/add_oid.html
{% include 'template.html' %} 
<form class="item" method="POST">
    {% csrf_token %}
    <p><strong>Pour ajouter un utilisateur : </strong></p>

    <p>Nom :</p>
    {{ form.name }}

    <p>OID :</p>
    {{ form.oid }}
    
    <p>Est un entier :</p>
    {{ form.is_Integer }}
    
    <p>Est une donnée fixe :</p>
    {{ form.Donnee_fixe }}
    
    <br/><br/>
    <input class="button_cursor" type="submit" name="add_oid" value="Ajouter un oid" />
    <br/><br/>
    <a href="{% url 'liste_oids' %}">Retour à la liste des OIDs</a>
</form>

configuration/templates/add_utilisateur.html
{% include 'template.html' %} 
<form class="item" method="POST">
    {% csrf_token %}
    <p><strong>Pour ajouter un utilisateur : </strong></p>

    <p>Login :</p>
    {{ form.login }}

    <p>Mot de passe :</p>
    {{ form.password }}

    <p>Nom de famille :</p>
    {{ form.last_name }}
    
    <p>Prénom :</p>
    {{ form.first_name }}
    
    <p>Est admin :</p>
    {{ form.is_admin }}
    
    <p>Mail :</p>
    {{ form.mail }}
    
    <br/><br/>
    <input class="button_cursor" type="submit" name="add_user" value="Ajouter un utilisateur" />
    <br/><br/>
    <a href="{% url 'liste_users' %}">Retour à la liste des utilisateurs</a>
</form>

configuration/templates/confirm_delete_graphique_machine.html
{% include 'template.html' %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmation de suppression</title>
</head>
<body>
    <h1>Êtes-vous sûr de vouloir supprimer {{ object.graphique }} de {{ object.machine }} ?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Oui, supprimer</button>
        <a class="btn btn-danger" href="{% url 'liste_oids' %}">Non, annuler</a>
    </form>
</body>
</html>

configuration/templates/edit_graphique.html
{% include 'template.html' %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier un graphique</title>
</head>
<body>
    <h1>Modifier le graphique</h1>

    <form method="post">
        {% csrf_token %}
        <p>Nom :</p>
        {{ form.name }}

        <p>Type de graphique :</p>
        {{ form.GraphiqueType }}
        
         <div id="axes-section" style="display:none;">
         <p>Axe x :</p>
         {{ form.axex }}
         
         <p>Axe y :</p>
         {{ form.axey }}
         </div>
         
         <p>OID 1 :</p>
         {{ form.OID1 }}
         
          <div id="oid2-section" style="display:none;">
             <p>OID 2 :</p>
             {{ form.OID2 }}
          </div>
         
          <div id="valeur-max-section" style="display:none;">
             <p>Valeur max :</p>
             {{ form.valeur_max }}
          </div>
          
           <p>Valeur en entrée </p>
           {{ form.type_de_donnees_entree }}
           
            <p>Valeur en sortie</p>
            {{ form.type_de_donnees_sortie }}
          
         <script>
         function toggleFields() {
             var typeSelect = document.querySelector("[name='GraphiqueType']");
             var selectedType = typeSelect.value;

             // Masquer ou afficher les champs en fonction du type sélectionné
             var showAxes = selectedType !== "Texte" && selectedType !== "Curseur";
             var showOID2 = selectedType !== "Texte" && selectedType !== "Curseur";
             var showValeurMax = selectedType !== "Texte" && selectedType !== "Fleche";

             document.getElementById('axes-section').style.display = showAxes ? 'block' : 'none';
             document.getElementById('oid2-section').style.display = showOID2 ? 'block' : 'none';
             document.getElementById('valeur-max-section').style.display = showValeurMax ? 'block' : 'none';
         }

         document.querySelector("[name='GraphiqueType']").addEventListener('change', toggleFields);

         // Exécuter la fonction au chargement de la page
         toggleFields();
         </script>
    
        <br/><br/>
        <input class="button_cursor" type="submit" name="edit_graphique" value="Modifier le graphique" />
        <br/><br/>
    <a class="btn btn-outline-primary" href="{% url 'liste_graphiques' %}">Retour à la liste des graphiques</a>
</body>
</html>

configuration/templates/edit_graphique_machine.html
{% include 'template.html' %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier un oid</title>
</head>
<body>
    <h1>Modifier l'oid</h1>

    <form method="post">
        {% csrf_token %}
        <p>Graphique :</p>
        {{ form.graphique }}

        <p>Machine :</p>
        {{ form.machine }}
        
         <p>Ordre:</p>
         {{ form.ordre }}
         
        </br></br>
        <button class="btn btn-success" type="submit">Mettre à jour</button>
    </form>

    <br>
    <a class="btn btn-outline-primary" href="{% url 'liste_graphiques' %}">Retour à la liste des graphiques</a>
</body>
</html>

configuration/templates/edit_machine.html
{% include 'template.html' %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier une Machine</title>
</head>
<body>
    <h1>Modifier la Machine</h1>

    <form method="post">
        {% csrf_token %}
        
    <p>Nom :</p>
    {{ form.name }}
    
    <p>Adresse IP :</p>
    {{ form.IPAdresse }}
    
    <p>Type SNMP :</p>
    {{ form.SNMPType }}
    
    <p>Communauté :</p>
    {{ form.Community }}
        <br><br>
        <button class="btn btn-success" type="submit">Mettre à jour</button>
    </form>

    <br>
    <a class="btn btn-outline-primary" href="{% url 'liste_machines' %}">Retour à la liste des machines</a>
</body>
</html>

configuration/templates/edit_oid.html
{% include 'template.html' %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier un oid</title>
</head>
<body>
    <h1>Modifier l'oid</h1>

    <form method="post">
        {% csrf_token %}
        <p>Nom :</p>
        {{ form.name }}

        <p>OID :</p>
        {{ form.oid }}
        
         <p>Est un entier :</p>
         {{ form.is_Integer }}
         
         <p>Est une donnée fixe :</p>
         {{ form.Donnee_fixe }}
    
        </br></br>
        <button class="btn btn-success" type="submit">Mettre à jour</button>
    </form>

    <br>
    <a class="btn btn-outline-primary" href="{% url 'liste_oids' %}">Retour à la liste des oids</a>
</body>
</html>

configuration/templates/liste_graphiques.html
{% include 'template.html' %} 
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liste des Graphiques</title>
</head>
<body>
    <h1>Liste des Graphiques</h1>
    <a class="btn btn-primary" href="{% url 'add_graphique' %}">Ajouter un graphique</a>
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col" >Suppressions</th>
                <th scope="col" >Editions</th>
                <th scope="col" >Nom</th>
                <th scope="col" >Type de graphique</th>
                <th scope="col" >Axe x</th>
                <th scope="col" >Axe y</th>
                <th scope="col" >OID 1</th>
                <th scope="col" >OID 2</th>
                <th scope="col" >Valeur max</th>
                <th scope="col" >Valeur en entree</th>
                <th scope="col" >Valeur en sortie</th>
            </tr>
        </thead>
        <tbody>
            {% for key, values in dictionary_graphiques.items %}
            <tr>
                <td><a class="btn btn-danger" href="{% url 'delete_graphique' key.id %}">Supprimer</a></td>
                <td><a class="btn btn-secondary" href="{% url 'edit_graphique' key.id %}">Editer</a></td>
                <td>{{ key.name }}</td>
                <td>{{ key.get_GraphiqueType_display }}</td>
                <td>{{ key.axex|default_if_none:'' }}</td>
                <td>{{ key.axey|default_if_none:'' }}</td>
                <td>{{ key.OID1.name }}</td>
                <td>{{ key.OID2.name }}</td>
                <td>{{ key.valeur_max }}</td>
                <td>{{ key.type_de_donnees_entree }}</td>
                <td>{{ key.type_de_donnees_sortie }}</td>
                <td>
                    <a class="btn btn-primary" href="{% url 'add_graphique_has_machine' key.id %}">Ajouter</a></br>
                    {% for v in values %}
                        <a class="btn btn-danger" href="{% url 'delete_graphique_has_machine' v.id %}">X  {{ v.machine }} </a><br>
                    {% endfor %}
                    </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    
     <h1>Gestion de l'affichage des graphiques par Machine</h1>
     {% for key, values in dictionary_machines.items %}
     <h2>Nom de la machine : {{key.name}}</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col" >graphique</th>
                <th scope="col" >Ordre</th>
                <th scope="col" >Edit</th>
            </tr>
        </thead>
        <tbody>
        {% for v in values %}
            <tr>
                <td>{{ v.graphique }}</td>
                <td>{{ v.ordre }}</td>
                <td><a class="btn btn-secondary" href="{% url 'edit_graphique_machine' v.id %}">Editer</a></td>
            </tr>
            {% endfor %}
        </tbody>    
      </table>  
      {% endfor %}
</body>
</html>